version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: mercer_hr
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/mercer_hr
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=your-secret-key-here
      - ADMIN_EMAIL=admin@mercer.com
      - ADMIN_PASSWORD=admin123
    depends_on:
      - postgres
      - redis
    volumes:
      - ./app:/app/app
      - ./uploads:/app/uploads

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/mercer_hr
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=your-secret-key-here
    depends_on:
      - postgres
      - redis
    volumes:
      - ./app:/app/app
      - ./uploads:/app/uploads

volumes:
  postgres_data: